<?php $this->parent('layout', ['foo' => 'hahaha']); ?>
<?php $this->start('menu'); ?>
<?php $this->include('menu'); ?>
<?php $this->end(); ?>
<?php $this->start('page_title'); ?>
<h1>Login form</h1>
<?php $this->end(); ?>
<?php $this->start('content'); ?>
<form method="POST">
	<input type="text" name="login" placeholder="Login" />
	<input type="password" name="password" placeholder="Password" />
	<button type="submit">Submit</button>
</form>
<?php $this->end(); ?>

Random login content
