<?php $this->parent(__DIR__ . '/layout.phtml', ['foo' => 'whatever']); ?>
<?php $this->start('menu'); ?>
<?php $this->include(__DIR__ . '/menu.phtml'); ?>
<?php $this->end(); ?>
<?php $this->start('page_title'); ?>
<h1>User info form</h1>
<?php $this->end(); ?>
<?php $this->start('content'); ?>
<form method="POST">
	<input type="text" name="first_name" placeholder="First name" />
	<input type="text" name="last_name" placeholder="Last name" />
	<button type="submit">Submit</button>
</form>
<?php $this->end(); ?>

Random user info content
