<?php $this->parent('layout', ['foo' => 'trololo']); ?>
<?php $this->start('menu'); ?>
<?php $this->include('menu'); ?>
<?php $this->end(); ?>
<?php $this->start('page_title'); ?>
<h1><?= $this->lc('Registration form'); ?></h1>
<?php $this->end(); ?>
<?php $this->start('content'); ?>
<form method="POST">
	<input type="text" name="login" placeholder="Login" />
	<input type="password" name="password" placeholder="Password" />
	<input type="password" name="password_repeat" placeholder="Password (repeat)" />
	<button type="submit">Submit</button>
</form>
<?php $this->end(); ?>
<?= $this->lolcase('Random register content'); ?>
